# Generated by Django 4.2.1 on 2023-07-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceX_Shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('size', models.CharField(max_length=50, verbose_name='size')),
                ('quantity', models.CharField(max_length=50, verbose_name='quantity')),
            ],
        ),
    ]
