# Generated by Django 4.2.1 on 2023-07-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceX_Shopping', '0007_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_id',
            field=models.CharField(max_length=50, verbose_name='id'),
        ),
    ]
