# Generated by Django 4.2.1 on 2023-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceX_Shopping', '0008_alter_cart_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cproduct_id',
            field=models.CharField(default=1, max_length=50, verbose_name='id'),
            preserve_default=False,
        ),
    ]
