# Generated by Django 4.2.1 on 2023-07-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SpaceX_Shopping', '0009_cart_cproduct_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cproduct_id',
        ),
    ]
